version: '3.8'
services:
  api:
    build: ./api-gateway
    ports:
      - "3000:3000"
    depends_on:
      - auth-service
      - data-service

  auth-service:
    build: ./auth-service
    ports:
      - "3001:3001"
    environment:
      - JWT_SECRET=mysecret     
    depends_on:
      - redis

  data-service:
    build: ./data-service
    ports:
      - "3002:3002"    
    depends_on:
      - redis

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
